// flow-typed signature: 3512ef1e89d0b84ddb2a2c277f1e6ca6
// flow-typed version: <<STUB>>/eslint-import-resolver-babel-plugin-root-import_v^1.1.1/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-import-resolver-babel-plugin-root-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-import-resolver-babel-plugin-root-import' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-import-resolver-babel-plugin-root-import/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-import-resolver-babel-plugin-root-import/src/index.js' {
  declare module.exports: $Exports<
    'eslint-import-resolver-babel-plugin-root-import/src/index',
  >;
}
