// flow-typed signature: 447b0a67dee1a37fe9805d763719df9f
// flow-typed version: <<STUB>>/flow_v^0.2.3/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow/examples/keystore' {
  declare module.exports: any;
}

declare module 'flow/examples/multi' {
  declare module.exports: any;
}

declare module 'flow/examples/serialForEach' {
  declare module.exports: any;
}

declare module 'flow/examples/simple' {
  declare module.exports: any;
}

declare module 'flow/flow' {
  declare module.exports: any;
}

declare module 'flow/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow/examples/keystore.js' {
  declare module.exports: $Exports<'flow/examples/keystore'>;
}
declare module 'flow/examples/multi.js' {
  declare module.exports: $Exports<'flow/examples/multi'>;
}
declare module 'flow/examples/serialForEach.js' {
  declare module.exports: $Exports<'flow/examples/serialForEach'>;
}
declare module 'flow/examples/simple.js' {
  declare module.exports: $Exports<'flow/examples/simple'>;
}
declare module 'flow/flow.js' {
  declare module.exports: $Exports<'flow/flow'>;
}
declare module 'flow/tests.js' {
  declare module.exports: $Exports<'flow/tests'>;
}
