// flow-typed signature: eae9f9fa1492118916b90662c831e13d
// flow-typed version: <<STUB>>/react-native-side-menu_v^1.1.3/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-side-menu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-side-menu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-side-menu/build/index' {
  declare module.exports: any;
}

declare module 'react-native-side-menu/build/styles' {
  declare module.exports: any;
}

declare module 'react-native-side-menu/libdefs' {
  declare module.exports: any;
}

declare module 'react-native-side-menu/styles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-side-menu/build/index.js' {
  declare module.exports: $Exports<'react-native-side-menu/build/index'>;
}
declare module 'react-native-side-menu/build/styles.js' {
  declare module.exports: $Exports<'react-native-side-menu/build/styles'>;
}
declare module 'react-native-side-menu/index' {
  declare module.exports: $Exports<'react-native-side-menu'>;
}
declare module 'react-native-side-menu/index.js' {
  declare module.exports: $Exports<'react-native-side-menu'>;
}
declare module 'react-native-side-menu/libdefs.js' {
  declare module.exports: $Exports<'react-native-side-menu/libdefs'>;
}
declare module 'react-native-side-menu/styles.js' {
  declare module.exports: $Exports<'react-native-side-menu/styles'>;
}
