export default {
  APP_STORAGE_KEY: '@MIND_CAST',
  PODCASTS_SAVED: 'PODCASTS_SAVED',
  HEADER_BUTTON_RIGHT_PLAYER_ACTION: 'HEADER_BUTTON_RIGHT_PLAYER_ACTION',
  NAVIGATE_PLAYER: 'NAVIGATE_PLAYER',
  PLAYER_PARAMS: 'PLAYER_PARAMS',
  PLAYER_TITLE_PARAM: 'PLAYER_TITLE_PARAM',
  IS_PLAYER_RIGHT_MENU_OPEN: 'IS_PLAYER_RIGHT_MENU_OPEN',
  NAVIGATE_AUTHOR_DETAIL: 'NAVIGATE_AUTHOR_DETAIL',
  AUTHOR_DETAIL_PARAMS: 'AUTHOR_DETAIL_PARAMS',
  SUBJECT_DETAIL_PARAMS: 'SUBJECT_DETAIL_PARAMS',
  SEARCH_AUTHOR_BY_NAME_PARAM: 'SEARCH_AUTHOR_BY_NAME_PARAM',
  PLAYLIST_KEY: 'PLAYLIST_KEY',

  NAVIGATE_PODCAST_DETAIL: 'NAVIGATE_PODCAST_DETAIL',
  PODCAST_DETAIL_PARAMS: 'PODCAST_DETAIL_PARAMS',
};
