const ROUTES = {
  SUBJECT_DETAIL: 'SUBJECT_DETAIL',
  PODCAST_DETAIL: 'PODCAST_DETAIL',
  AUTHOR_DETAIL: 'AUTHOR_DETAIL',
  PLAYER: 'PLAYER',
};

const PARAMS = {
  SEARCH_AUTHOR_BY_NAME: 'SEARCH_AUTHOR_BY_NAME',
  PLAYLIST_TITLE: 'PLAYLIST_TITLE',
  SUBJECT_DETAIL: 'SUBJECT_DETAIL',
  PODCAST_DETAIL: 'PODCAST_DETAIL',
  AUTHOR_DETAIL: 'AUTHOR_DETAIL',
  PLAYER_TITLE: 'PLAYER_TITLE',
  PLAYER: 'PLAYER',
};

const KEYS = {
  PLAYLIST_STORAGE_KEY: 'PLAYLIST_STORAGE_KEY',
  APP_STORAGE_KEY: '@MIND_CAST',
  PODCASTS_SAVED: 'PODCASTS_SAVED',
  HEADER_BUTTON_RIGHT_PLAYER_ACTION: 'HEADER_BUTTON_RIGHT_PLAYER_ACTION',
  IS_PLAYER_RIGHT_MENU_OPEN: 'IS_PLAYER_RIGHT_MENU_OPEN',
  SHOULD_SHUFFLE_PLAYLIST: 'SHOULD_SHUFFLE_PLAYLIST',
  PLAYLIST: 'PLAYLIST',
  PODCAST_DETAIL_SHOULD_SHOW_AUTHOR_SECTION:
    'PODCAST_DETAIL_SHOULD_SHOW_AUTHOR_SECTION',
};

export default {
  ROUTES,
  PARAMS,
  KEYS,
};
